### PR TITLE
Upgrade packages

### PR DESCRIPTION
**Pull request by chriswoodle**
Decorators do not compile in Typescript 5, upgrading the deps resolves the issue.

Upgrades to support in Typescript 5 decorator changes: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html

### CODE REVIEW

**Comment by KieronWiltshire** [comment]
Any chance of this getting merged?

**Comment by erikc5000** [comment]
Sorry for the delay -- this looks fine. I'll try to get a new release out soon.

**Comment by KieronWiltshire** [comment]
> Sorry for the delay -- this looks fine. I'll try to get a new release out soon.

Please make a release ASAP. Want to use this instead of making my own.

**Comment by amirjani** [comment]
@erikc5000 can you please release this package?

**Pull request merged**
